### ISSUE TITLE
Mobile Footer text alignment broken

### ISSUE THREAD

**Issue by subeshb1** [subeshb1/developer-community-stats#133]
## Description

The footer layout for mobile has broken text alignment:

<img width="418" alt="Screen Shot 2020-10-16 at 13 46 24" src="https://user-images.githubusercontent.com/27361350/96229019-15d9ec80-0fb6-11eb-93cd-9b1fd9b3809d.png">

The**Made With** text and copyright text overlap each other. We need to fix the alignment.

## Acceptance criteria
* Make sure the text doesn't align in mobile layout
* Ensure the copyright text goes below the Made with content

**Comment by dimlaksana** [comment]
Can you assign this to me? I'll work on this

**Comment by subeshb1** [comment]
Yes @dimlaksana . I'll assign it to you. Be sure to post regular updates if you face any challenge or difficulties

**Comment by subeshb1** [comment]
@dimlaksana will you be able to do it ?

**Comment by dimlaksana** [comment]
Yes, I'm working on this right now

**Comment by subeshb1** [comment]
Ok thanks for the update!

**Comment by subeshb1** [comment]
Hi @dimlaksana any update on this? It's ok if you get stuck we can assign it to someone else

**Comment by dimlaksana** [comment]
I'm done. I've made a PR #164

**Comment by subeshb1** [comment]
Fixed by #164. Thanks @dimlaksana
