### ISSUE TITLE
Navbar menu not visible on Mobile 

### ISSUE THREAD

**Issue by dimlaksana** [subeshb1/developer-community-stats#167]
So when I was working on #133, I noticed some bugs:

- `Navbar menu`  is not visible on mobile web version.

![Screenshot_20201017_0025401](https://user-images.githubusercontent.com/57056689/96281209-fe315100-1013-11eb-9941-c80aa8a499d8.png)

- and what is the purpose of this blank space below the `footer`? 

![Screenshot_20201017_004927](https://user-images.githubusercontent.com/57056689/96281481-57998000-1014-11eb-92b2-ddc82460d4d4.png)

I can work on this, assign me this issue I'll fix it.

**Comment by subeshb1** [comment]
Hi @dimlaksana. Actually, the design for mobile is not quite complete and needs a lot of improvements. I can use some help! 
Will be more than happy to have this designed properly. The theme picker was left out on purpose, assuming that it will have a design that fitted in the mobile view. You can suggest and add the view. Thanks! :)
