### ISSUE TITLE
Mobile Navbar covers first developer card content

### ISSUE THREAD

**Issue by subeshb1** [subeshb1/developer-community-stats#201]
## Description 
The mobile navbar covers the first developer card information. 

**Current Behaviour**:
<img width="369" alt="Screen Shot 2020-10-17 at 10 38 10" src="https://user-images.githubusercontent.com/27361350/96328652-25643e80-1065-11eb-9604-c9983031bcda.png">

**Expected Behaviour**:
<img width="367" alt="Screen Shot 2020-10-17 at 10 38 46" src="https://user-images.githubusercontent.com/27361350/96328653-2dbc7980-1065-11eb-80ee-25d0946e131a.png">

Make sure that the navbar doesn't hide information for first developer card.

## Acceptance criteria
* Navbar should be properly aligned
* Screenshot of the changes should be in the PR
* It should not break the desktop navbar

**Comment by b2pacific** [comment]
Can I work on this issue?

**Comment by subeshb1** [comment]
Yes, @b2pacific. Be sure to post updates if you get stuck

**Comment by b2pacific** [comment]
Can you please tell me the command you that you told me to run when I was getting that error last time.
I forgot that command

**Comment by subeshb1** [comment]
```
ENV_TYPE=mock gatsby develop
```

**Comment by b2pacific** [comment]
![Screenshot from 2020-10-17 11-21-36](https://user-images.githubusercontent.com/52305879/96329522-665f5180-106b-11eb-927f-2e91b2b8a5bc.png)
