### ISSUE TITLE
Add some suggestions and feature request (Open for everyone)

### ISSUE THREAD

**Issue by subeshb1** [subeshb1/developer-community-stats#202]
## Description
If you have suggestions or feedback regarding the design of the website, repository structure please let me know in this issue. Any feedback would be highly appreciated. You can:
* suggest change,
* add your design,
* or simply comment on your thoughts,
* and share what you've learned

**Comment by sadakchap** [comment]
Maybe adding smooth transition effect on card hover

**Comment by subeshb1** [comment]
Yes, that seems like a nice idea! Thanks @sadakchap! Will create an issue for it

**Comment by sadakchap** [comment]
@subeshb1 , can I work on that issue?

**Comment by subeshb1** [comment]
Yes, sure! Here is the link #205

**Comment by tooshar** [comment]
### **A Suggestion:**
@subeshb1, in **_Change Website Theme_** menu , after we click on **Show more** button, the height of the menu exceeds the page height (when not zoomed out). We should have a **scrollbar** in the menu.

**Comment by tooshar** [comment]
### Bug Report:
When I click/set **Dark** as Theme in **_Change Website Theme_** menu, the font-color of texts in dropdowns, input boxes, become white, and gives a feel of blank selections.

**Comment by subeshb1** [comment]
Hi, @tooshar Thanks for the suggestion. Do you mean the view is not displayed in the mobile view?
I can create an issue if you can explain more.


And for the Bug report can you create an issue with screenshots to clarify more?

**Comment by sadakchap** [comment]
### Suggestion
![image](https://user-images.githubusercontent.com/44117648/96359764-21ebb880-1134-11eb-99ae-a838762a9ce1.png)
Can we remove these vertical scollbars as we don't use it(disabled by browsers because very little content overflow).

**Comment by subeshb1** [comment]
Yes sure @sadakchap. Can you create an issue and submit a fix?

**Comment by tooshar** [comment]
@subeshb1 try to do **CTRL + +**, after opening the change website theme menu and expanding the more options, you will see the extra options get hidden and go out of view. I am not sure for mobile view.

And for the bug, I will create an issue, with explanation.

**Comment by sadakchap** [comment]
> Yes sure @sadakchap. Can you create an issue and submit a fix?

Sure @subeshb1 , there is the [issure](https://github.com/subeshb1/developer-community-stats/issues/245)

**Comment by subeshb1** [comment]
@tooshar Thanks for the suggestions and bug report. I have addressed them

**Comment by suffisme** [comment]
Sorry, I couldn't find link for the website. Can you please share it again?
I am getting interested in contributing.

**Comment by subeshb1** [comment]
Yes sure, Here it is: https://developer-community-stats.netlify.app/

**Comment by abhishekpatel946** [comment]
added a little bit hover effect with transition and transform on each card & also hovor-effect on the buttons on the top of the main page.

**Comment by Rebaiahmed** [comment]
- > **Feature sugeestion1** : What about adding pagination in the place of scrolling to the end of the page ?
- > **Feature sugeestion 2** :  Filtring and sorting by number of pull requests of user  ?
- > **Feature sugeestion 3** :  Making stats page : Per country , Per technologies , Per respositories  ?

**Comment by subeshb1** [comment]
Hi, @Rebaiahmed Thanks for the suggestions. I will be creating issues for them shortly. If you are free and willing to contribute on these issues please feel free to create an issue for each suggestion and submit the change in PR.

**Comment by HiruniPerera** [comment]
Hi can i work on this? would love to contribute
