### ISSUE TITLE
Update the corn schedule time of daily build to 4hrs

### ISSUE THREAD

**Issue by subeshb1** [subeshb1/developer-community-stats#203]
## Description 
Currently, the daily build cron is scheduled to run every 12 hours. Change it to run 4 hours.

## Reference:
```
.github/workflows/main_deploy.yaml
```

**Comment by sadakchap** [comment]
Hi @subeshb1 , I would like to work on it. may I?

**Comment by subeshb1** [comment]
Yes sure! Go ahead @sadakchap

**Comment by sadakchap** [comment]
Hey, I tried changing cron schedule to 4 hours, in this [PR](https://github.com/subeshb1/developer-community-stats/pull/207) .

Please, have a look and let me know😃

**Comment by subeshb1** [comment]
Thanks! We can monitor this in the Actions tab to see if it's working or not. Great job!
