### ISSUE TITLE
Add animation to hover effect on Developer card

### ISSUE THREAD

**Issue by subeshb1** [subeshb1/developer-community-stats#205]
## Description
Currently, when the developer card is hovered over by a mouse, it shows a link to go to the profile page. We had a suggestion to add smooth transitions to it.

## Acceptance criteria
* Make a smooth transition to show a link to go to profile page when Developer card is hovered. (Feel free to use your creativity)
* The theme changes color should apply as well
* Add a GIF to show the changes

**Comment by sadakchap** [comment]
Hi @subeshb1 ,  can I help to add smooth transition effects?

**Comment by Malvika18** [comment]
hey can i contribute to this

**Comment by subeshb1** [comment]
I assigned this to @sadakchap

**Comment by subeshb1** [comment]
Hi @Malvika18 sorry this was assigned. You looked at others issues: https://github.com/subeshb1/developer-community-stats/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22

or you can create your own by providing suggestions

**Comment by sadakchap** [comment]
Hi @subeshb1 , I tried these 2 transition -
- this is simple smooth transition
![9VFsLMowIr](https://user-images.githubusercontent.com/44117648/96330572-d07bf480-1073-11eb-9d97-325bc14e1d08.gif)

- this transition has a little zoom effect 
![UMtoRcWJBy](https://user-images.githubusercontent.com/44117648/96330594-fc977580-1073-11eb-8f80-60d2dfc421c4.gif)

Please, let me know which one should I implement?

**Comment by subeshb1** [comment]
This is great work @sadakchap! I like the first one :)

**Comment by subeshb1** [comment]
Fixed by #216
