### ISSUE TITLE
Add filters and sorters for sorting and filtering users 

### ISSUE THREAD

**Issue by subeshb1** [subeshb1/developer-community-stats#231]
## Description
As the number of contributors is growing and it's quite hard to find one's own profile, we need a feature to sort and filter out users. It is to be done on the client-side. 
The filterable fields are:
1. Github user name
2. User name
3. Country

The sortable fields are:
1. Country
2. Github user name
3. User name
4. Total commits (this year)
5. Followers

## Acceptance criteria
* The above-listed fields should be filterable and sortable as listed.
* The filtering should be done on the client-side. (All the contributor data is present in UI as JSON)
* Add form fields to filter and sort.

## Reference

```
src/pages/index.js
```

**Comment by Abhikumar98** [comment]
@subeshb1 I can take this up.

**Comment by subeshb1** [comment]
Yes sure @Abhikumar98. Be sure to post updates if you get stuck or need clarification

**Comment by Abhikumar98** [comment]
Hey @subeshb1 , getting this error while trying to start run the project in local.   
`Cannot query field "allContributor" on type "Query".`.   
Could you help me out here ?

**Comment by subeshb1** [comment]
Use the following for development 
```
ENV_TYPE=mock gatsby develop
```

The project uses github graphql api to fetch user stats. So it requires Github token . The above command mocks github api
@Abhikumar98

**Comment by subeshb1** [comment]
Fixed bt #237. Thanks a lot @Abhikumar98 for your wonderful work.

**Comment by Abhikumar98** [comment]
@subeshb1 Most welcome 😄
