### ISSUE TITLE
User Interface broken after addition of ant-d

### ISSUE THREAD

**Issue by subeshb1** [subeshb1/developer-community-stats#240]
## Description

After the introduction of the ant-d package to add filters, the existing interface design has broken.

### Examples:

**Before**
<img width="467" alt="Screen Shot 2020-10-18 at 07 57 13" src="https://user-images.githubusercontent.com/27361350/96357152-aaa82b80-1117-11eb-96cd-026544ae5c21.png">

**Present**
<img width="482" alt="Screen Shot 2020-10-18 at 07 54 56" src="https://user-images.githubusercontent.com/27361350/96357151-a5e37780-1117-11eb-8e4a-0a5cd4ee5fa4.png">

There seems to be unnecessary padding, margin, and fonts that have been overridden.
We need to make importing ant-d doesn't break other UI interfaces.

## Acceptance criteria
* Make sure the UI is not broken by ant-d css

**Comment by subeshb1** [comment]
It looks like adding ant-design has overridden the styles of the website.

Before:
<img width="1437" alt="Screen Shot 2020-10-18 at 11 02 39" src="https://user-images.githubusercontent.com/27361350/96359340-78a3c300-1131-11eb-9a35-6216dd6cb592.png">

After:
<img width="1438" alt="Screen Shot 2020-10-18 at 11 02 29" src="https://user-images.githubusercontent.com/27361350/96359344-80636780-1131-11eb-8391-99337f607797.png">

The alignments have also broken in navbar and font size changes in the footer


Do you know a way to prevent ant-design to override global styles?

@Abhikumar98

**Comment by subeshb1** [comment]
We might have to remove ant-design

**Comment by Abhikumar98** [comment]
@subeshb1  I've fixed the styling issues caused by due to antd.

**Comment by subeshb1** [comment]
@Abhikumar98 
We might have to look for an alternative to `ant-design`

In dark mode, the theme picker inputs color is overridden and shown white. 

The font's in the footer are smaller.

The icons size have been made smaller

The padding in div has been changed

Since we have a lot of issues, it's better to use another library or build our own.

**Comment by Abhikumar98** [comment]
@subeshb1  Got it. 
I'll look into this.

**Comment by subeshb1** [comment]
Thanks, @Abhikumar98. Happy to have you as a contributor :)

**Comment by subeshb1** [comment]
I'll be removing ant-design for now until we look for another alternative

**Comment by subeshb1** [comment]
Closing this as this has been stale for 2 days. Revisiting this idea
