### ISSUE TITLE
Remove disabled vertical scrollbar

### ISSUE THREAD

**Issue by sadakchap** [subeshb1/developer-community-stats#245]
### Description

Remove vertical scrollbar in **Change website theme** menu.

![image](https://user-images.githubusercontent.com/44117648/96359976-26b16c00-1136-11eb-9286-6283484dea13.png)

**Comment by sadakchap** [comment]
Hi @subeshb1 , tried these two things - 
- It doesnt have any unwanted scrollbars
![image](https://user-images.githubusercontent.com/44117648/96360824-2a48f100-113e-11eb-9c69-8a924d8be963.png)

- It does not have only vertical scrollbar
![image](https://user-images.githubusercontent.com/44117648/96360848-5e241680-113e-11eb-9488-f6e23629841d.png)

Which one do you like?

**Comment by subeshb1** [comment]
Cant, we do overflow auto for both? @sadakchap

**Comment by sadakchap** [comment]
Yep @subeshb1 , first one is `overflow:auto` and second one is `overflow: scroll hidden`.
So, should we go for first one?

**Comment by subeshb1** [comment]
Yes let's go with first.

**Comment by subeshb1** [comment]
Fixed by #255
