### ISSUE TITLE
After Selecting Dark Mode, the labels disappear

### ISSUE THREAD

**Issue by tooshar** [subeshb1/developer-community-stats#248]
### Description
Please refer the image, all input fields lose their selected value.

![image](https://user-images.githubusercontent.com/26686938/96360993-82ccbe00-113f-11eb-846d-559cfc3ea5a2.png)

**Comment by tooshar** [comment]
@subeshb1 , I would like to fix and close this issue.

**Comment by tooshar** [comment]
Got reference of a parent [issue](https://github.com/subeshb1/developer-community-stats/issues/240), 
from https://github.com/subeshb1/developer-community-stats/issues/240#issuecomment-711121973

**Comment by subeshb1** [comment]
Thanks for reporting this @tooshar. It looks like importing a package `ant-design` was the root cause of UI breaking. @Abhikumar98  is looking to fix it

**Comment by subeshb1** [comment]
This has been fixed
