### ISSUE TITLE
New trial

### ISSUE THREAD

**Issue by KeefeKoh** [subeshb1/developer-community-stats#267]
"<guthub_username>": {
   "country": "Your Country", // Required
   "name": "Your Name", // Required
   "linkedin": "linkedin URL", // Optional
   "twitter": "twitter URL", // Optional
   "website":"website or blog URL"//Optional
}

**Comment by subeshb1** [comment]
Hi @KeefeKoh did you meant to create a Pull request instead?

**Comment by subeshb1** [comment]
Closing this
