### ISSUE TITLE
Prevent main branch github action to run on non code base files

### ISSUE THREAD

**Issue by subeshb1** [subeshb1/developer-community-stats#281]
## Description
The deploy action gets triggered on push to master. But it also runs when changes in Readme files and non deploy needing files. 

Update the action to prevent deploy on pushes to those files:

```
.github/workflows/main_deploy.yaml
```

**Comment by msriaz** [comment]
@subeshb1 I would love to contribute on this issue, please assign it to me.

**Comment by subeshb1** [comment]
Yes sure @msriaz . Be sure to post updates regularly

**Comment by msriaz** [comment]
Please check [this PR](https://github.com/subeshb1/developer-community-stats/pull/462) for the fix of this issue.

**Comment by subeshb1** [comment]
Fixed
