### ISSUE TITLE
Add filters 

### ISSUE THREAD

**Issue by subeshb1** [subeshb1/developer-community-stats#370]
## Description
This is a revision to #231, where filters and sorters were added. However, it used a package `ant-design` that broke all the websites UI and imported unnecessary CSS. We had to revert the changes. Currently, there are sorters that when clicked sorts the lists accordingly.

We need to add the following filters:
1. Github user name
2. Country
3. User name

The design is open for suggestions.

## Acceptance criteria
* Filters must be responsive and easy to use
* If external packages are used, they must not alter the site's styles
* Screenshot and GIF in the PR

**Comment by ronlaniado** [comment]
Can I try to tackle this one?

**Comment by subeshb1** [comment]
yes sure. @ronlaniado be sure to keep us updated

**Comment by ronlaniado** [comment]
To be clear, we want to add functionality to be able to search by country or username?

**Comment by subeshb1** [comment]
Both. Currently, we can search by GitHub user name. Now we want a feature to search or filter by country as well.

**Comment by ronlaniado** [comment]
I have added this feature here #485

**Comment by subeshb1** [comment]
Thanks @ronlaniado
