### ISSUE TITLE
Create a page to show repository statistics 

### ISSUE THREAD

**Issue by subeshb1** [subeshb1/developer-community-stats#424]
## Description 
As the repository and number of contributor grows, it will be really good to see the growth in numbers. Create a page that shows the following statistics:
* Number of users per country 
* Total number of contributors
* Highest contributors (Top 10) based on Pr and issues worked on
* graph showing number of contributors per day
* number of users joined per day

**Comment by MissyM2** [comment]
can I try this one?

**Comment by subeshb1** [comment]
Yes, sure @MissyM2 . Be sure to post regular updates

**Comment by subeshb1** [comment]
Hi @MissyM2 Any updates on this? Will you be taking this?

**Comment by MissyM2** [comment]
Hi, there, I will try this.  I will update you by 5 pm est.

**Comment by subeshb1** [comment]
Sure @MissyM2. Thank you!

**Comment by MissyM2** [comment]
Just a little update that I got the app running locally and, as you saw, I added myself as a contributor and a profile.  I have looked over the code but I will not really begin to work on this until later this afternoon.

**Comment by subeshb1** [comment]
It's ok @MissyM2 Take as much time as you need, just keep us posted with updates like this so that we know it's being worked on. And thank you so much for this :)

**Comment by MissyM2** [comment]
hi, @subeshb1 I am sorry I haven't made progress on this.  I got bogged down with work.  I should have time this week.  I know Hacktoberfest is over but I am interested in this project.  Is it OK if I continue to work on it?

**Comment by subeshb1** [comment]
Yes, sure @MissyM2. Thanks for putting time into it. You can continue working on it 😄
