### ISSUE TITLE
Add github action to automatically sort 

### ISSUE THREAD

**Issue by subeshb1** [subeshb1/developer-community-stats#63]
## Description
New users are getting confused sorting their stats in `contributors.json`. It is cumbersome to do it manually. Create an action that sorts the file in ascending order and commits the file in the same pr.

## Acceptance criteria
* Sort the file in ascending order if not.
* The spec should only be run after the commit and check id made.

## Reference:
```
.github/workflows/contributor_spec.yaml
```

**Comment by shankar524** [comment]
I would like top address this issue.

**Comment by shankar524** [comment]
@subeshb1  Has this issue been sorted?

**Comment by subeshb1** [comment]
No @shankar524. Closed this as no one there was to pick it up and had been dangling
