### ISSUE TITLE
Fix internal links not clicking

### ISSUE THREAD

**Issue by subeshb1** [subeshb1/developer-community-stats#75]
## Description
The internal links in the card shown on the home page don't point to the respective links. They instead redirect to the user's profile. We need to make sure that the links in Icon are clickable and point to respective pages. The problem is caused by nesting links within a link. Try to figure out a way to make both links interactable.

## Acceptance criteria
* When clicked on the icon, the link should open
* When clicked on anywhere in the card except the icons, it should open the profile page of the user

## Reference
```
src/components/DeveloperCard/index.jsx
```

**Comment by binismail** [comment]
can I work on it ?

**Comment by subeshb1** [comment]
@binismail Yes sure. Let me clarify the issue more

**Comment by subeshb1** [comment]
@subeshb1 do let me know if you understand the issue or not. I will assign you once you confirm

**Comment by binismail** [comment]
@subeshb1 yeah I do understand.

**Comment by subeshb1** [comment]
Hi @binismail any update on this?

**Comment by binismail** [comment]
Hi, @subeshb1 am working on it, although I ran into some error because I can't find the exact code written I don't know if you can guide me more.

**Comment by subeshb1** [comment]
No worries @binismail. The files is `src/components/DeveloperCard/index.jsx` The developer card needs to be modified. Do let me know if you have any problem

**Comment by binismail** [comment]
okay, thanks

**Comment by binismail** [comment]
I will work on it as soon as am back from work today.

**Comment by subeshb1** [comment]
Sure @binismail. Take your time

**Comment by subeshb1** [comment]
Fixed!
