### ISSUE TITLE
Create your first PR / Join Developer Community Stats

### ISSUE THREAD

**Issue by subeshb1** [subeshb1/developer-community-stats#8]
## Description
On the occasion of Hacktoberfest and to help beginners who have just started to get there hands dirty with GIt and Github, this repository is to guide newcomers and open source enthusiasts to come together and contribute. 
The first issue is really simple, you only have to add the following fields in `contributor.json` file:
```js
"<guthub_username>": {
   "country": "Your Country", // Required
   "name": "Your Name", // Required
   "linkedin": "linkedin URL", // Optional
   "twitter": "twitter URL", // Optional
   "website":"website or blog URL"//Optional
}
```

Here is a reference from an early contributor: https://github.com/subeshb1/developer-community-stats/pull/22

## Steps
1. Fork the repository
2. Clone the repository you have forked (Appears in the repository section of your profile)
3. Checkout to a new branch. (Optional if you don't have a concept of branching)
4. Change in `contributor.json` add your information in the above json object. **Note: Make sure you place your information in the correct order according to the GitHub user name in ascending order ignoring case sensivity.** This is done to avoid many merge conflicts. If you don't want to do it manually, you can use the following command: 
 ```
npx sort-json contributors.json --ignore-case
```
5. Commit the changes
6. Create a PR to the original repository
Here's how to do it:
**Step 1:** Go to Code section of forked repo an click on Pull request below the `Code` Button besides `Compare` Button
<img width="1047" alt="Screen Shot 2020-10-03 at 07 50 41" src="https://user-images.githubusercontent.com/27361350/94980913-a42d8780-054d-11eb-8165-34c671820bcb.png"> **Step 2:** Make sure the following is branches are selected: <img width="1081" alt="Screen Shot 2020-10-03 at 07 51 31" src="https://user-images.githubusercontent.com/27361350/94981077-f0c59280-054e-11eb-98db-c98fd1449457.png">

Here is a guide/lab if you haven't created any commits or  PRs: 
https://subeshbhandari.com/blog/git-and-github-practical-for-beginners

**If you get stuck in any step feel free to tag me and request help**

**PS: Feel free to star the repository and follow me :)**

After this, your PR will be reviewed and once all the checks pass it will be merged to master. The PR will we then labeled as `hacktoberfest-approved`

## Outcome of this issue
* Collaboration and contribution to open source
* Experience continuous integration of code changes in a repository
* Be a part of Developer Community Stats

## Repository Context
This repository shows the Github stats of every contributor that has contributed to the above file. In the future, more detailed stats will be shown for each individual contributor. For now, it only shows basic stats, for example, total contribution this year, followers, number of pull requests, repository count, etc. Once your PR gets merged it will be shown on the Website:
https://developer-community-stats.netlify.app/

<img width="1434" alt="Screen Shot 2020-10-03 at 20 25 48" src="https://user-images.githubusercontent.com/27361350/94994327-a11ab180-05b6-11eb-9d83-b00fd836bf23.png">

**Comment by abhijeetekad** [comment]
thank you ..i am beginner .. i just made PR in your repository for hactoberfest...

**Comment by subeshb1** [comment]
Hi @abhijeetekad. This is a great way to getting started with open source. It looks like your PR has not been created.

You will need to create a new PR for the original repo. 
Here's how to do it:

Step 1: Go to Code section of forked repo an click on Pull request below the `Code` Button besides `Compare` Button
<img width="1047" alt="Screen Shot 2020-10-03 at 07 50 41" src="https://user-images.githubusercontent.com/27361350/94980913-a42d8780-054d-11eb-8165-34c671820bcb.png">


Step 2: Make sure the following is branches are selected:
<img width="1081" alt="Screen Shot 2020-10-03 at 07 51 31" src="https://user-images.githubusercontent.com/27361350/94981077-f0c59280-054e-11eb-98db-c98fd1449457.png">


The base should be the original repository and base branch master.
The head repository should be the forked repository and the head branch `HACTORBERFEST`

Feel free to ask more if you get stuck

**Comment by abhijeetekad** [comment]
Thank you sir for notifying me about my mistake ..

**Comment by aortiz24** [comment]
Can I be assigned this? It's my first time at Hacktoberfest!

**Comment by abhijeetekad** [comment]
Yaa 👍👍

**Comment by isabellabond** [comment]
Hello, I updated contributors.json for Hacktoberfest #48
Thank you

**Comment by isabellabond** [comment]
Whoops, resubmitted a pull request since the last one was in the wrong order #50
Thank you and happy Hacktoberfest

**Comment by isabellabond** [comment]
3rd times a charm #51
