### ISSUE TITLE
Add a link to nav bar icon pointing to this repository

### ISSUE THREAD

**Issue by subeshb1** [subeshb1/developer-community-stats#87]
## Description
When the Github icon on the navbar is clicked, direct it to this repository.

**Comment by subeshb1** [comment]
Sure @ellu-laitinen

**Comment by femakin** [comment]
Can I still work on this

**Comment by subeshb1** [comment]
@femakin This has already been assigned. If there is no response within 24 hrs I will assign it to you

**Comment by femakin** [comment]
@subeshb1 Alright but can you please share some beginner projects I can contribute to as this is my first experience.

**Comment by subeshb1** [comment]
Fixed by #90
